etcd:
  image: elcolio/etcd:latest
  container_name: etcd
  ports:
    - "2379:2379"
    - "4001:4001"

vulcand:
  container_name : vulcand
  image: mailgun/vulcand:v0.8.0-beta.2
  ports:
    - "8181:8181"
    - "8182:8182"
  links:
    - etcd
  command: /go/bin/vulcand -apiInterface=0.0.0.0 --etcd=http://etcd:4001


vulcaningress:
  container_name: vulcaningress
  image: zekizeki/vulcaningress:0.0.9
  links:
    - etcd
  environment:
    - ETCD_HOST=etcd
    - ETCD_PORT=2379
    - DOMAIN=.kubernetes
    - KUBE_API_URL=https://hocs-npa.ipttools.io/r/projects/1a16558/kubernetes/api
    - KUBE_API_USER=798FD01CF371EC7B6E06
    - KUBE_API_PASSWORD=Y33FKW5RfhtRJKpoK1U4xZRxbBXSqWABedusCWqi
    

