apiVersion: v1
kind: ReplicationController
metadata:
  name: webtest2
spec:
  replicas: 1
  selector:
    name: webtest2
  template:
    metadata:
      labels:
        name: webtest2
    spec:
      containers:
      - name: webtest2
        image: bungoume/debug-server:latest
        ports:
          - containerPort: 80
          
---            
            
apiVersion: v1
kind: Service
metadata:
  name: webtest2
  labels:
    name: webtest2
    type: ingress
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: webtest2